# Documentation https://github.com/Smile-SA/elasticsuite/wiki/ServerConfig-7.x
FROM elasticsearch:7.12.0
RUN cd /usr/share/elasticsearch \
    && bin/elasticsearch-plugin install analysis-phonetic \
    && bin/elasticsearch-plugin install analysis-icu

